GET http://localhost:6200/api/users HTTP/1.1


###
GET http://localhost:6200/api/users/top HTTP/1.1


###
GET http://localhost:6200/api/users/top/3 HTTP/1.1

###
POST http://localhost:6200/api/users/user HTTP/1.1
content-type: application/json

{
    "user":{
        "name":"user3",
        "flat":"203"
    }
}

###
PUT http://localhost:6200/api/users/user/5b9956e73a343e6a0e052bd8 HTTP/1.1
content-type: application/json

{
    "user":{
        "name":"user3_new",
        "flat":"203",
        "score":30
    }
}

###
POST http://neurobackend.herokuapp.com/public/api/users/authenticate HTTP/1.1
content-type: application/json

{
    "user":{
        "email":"c1@test.com",
        "password":"test"
    }
}


###
GET http://neurobackend.herokuapp.com/health-check HTTP/1.1
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViMTQyZDVjM2M2MjQ2MDA0MmFhOWM0ZiIsImlhdCI6MTUyODA2NDc3NCwiZXhwIjoxNjE0NDY0Nzc0fQ.odu8q2npTCARoaLhXS3efWOUJc_CbCReHzRTwjtrSpM