POST https://neurobackend.herokuapp.com/public/api/users HTTP/1.1
content-type: application/json

{
    "user":{
        "name":"test",
        "email":"test@test.com",
        "password":"test"
    }
}

###
POST http://neurobackend.herokuapp.com/public/api/users/authenticate HTTP/1.1
content-type: application/json

{
    "user":{
        "email":"test@test.com",
        "password":"test"
    }
}


###
GET http://neurobackend.herokuapp.com/health-check HTTP/1.1
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViMTQyZDVjM2M2MjQ2MDA0MmFhOWM0ZiIsImlhdCI6MTUyODA2NDc3NCwiZXhwIjoxNjE0NDY0Nzc0fQ.odu8q2npTCARoaLhXS3efWOUJc_CbCReHzRTwjtrSpM